import fs from 'node:fs';
import prettier from "prettier";


const baseColors = {
  "neutral-100": "#fffefc",
  "neutral-300": "#d4d1cb",
  "neutral-500": "#736b7a",
  "neutral-700": "#28232c",
  "neutral-900": "#1b171f",
  "blue-100": "#e6ebf5",
  "blue-300": "#8eaadc",
  "blue-400": "#2864dc",
  "blue-500": "#26417b",
  "blue-700": "#192a52",
  "blue-900": "#0f1a33",
  "orange-100": "#fff4e6",
  "orange-300": "#ffcf96",
  "orange-500": "#ffb155",
  "orange-700": "#c77e24",
  "orange-900": "#824f11",
  "green-100": "#e2f5ee",
  "green-300": "#68c79f",
  "green-500": "#177b51",
  "green-700": "#105237",
  "green-900": "#0a3322",
  "purple-100": "#f2e9f7",
  "purple-300": "#b08cc2",
  "purple-500": "#6b358a",
  "purple-700": "#4a2161",
  "purple-900": "#2d103d",
  "red-100": "#ffede9",
  "red-300": "#fe9f87",
  "red-500": "#fd5d36",
  "red-700": "#c23815",
  "red-900": "#80230b"
} as const;
const themeNames = ['light', 'dark'] as const;
const themes: ColorPalette = {
  background: { light: 'neutral-100', dark: 'neutral-700' },
  text: { light: 'neutral-700', dark: 'neutral-100' },
  border: { light: 'neutral-500', dark: 'neutral-300' },
  'cta-background': { light: 'blue-500', dark: 'orange-500' },
  'cta-text': { light: 'neutral-100', dark: 'neutral-700' },
  'accent-a': { light: "blue-500", dark: 'blue-500' },
  'accent-b': { light: "green-500", dark: 'green-500' },
  'accent-c': { light: "purple-500", dark: 'purple-500' },
  'accent-d': { light: "red-500", dark: 'red-500' },
  'link': { light: 'blue-400', dark: 'orange-500' }

}

type ThemeName = typeof themeNames[number];
type ColorKey = keyof typeof baseColors;
type ColorPalette = Record<string, Record<ThemeName, ColorKey>>

const buildCSSString = (assignments: String[], comment: String) => {
  // console.log(assignments)
  return `
  /* ${comment} */
  ${assignments.map(item => item + ";\n").join("")}
  `
}

const generateCSS = () => {
  const baseValues = []
  const themeValues: Record<ThemeName, String[]> = {}
  const themeLocals: Record<ThemeName, String[]> = {}
  // initialize themeValues
  for (const themeName of themeNames) {
    themeValues[themeName] = [];
    themeLocals[themeName] = [];
  }

  // build base values
  for (const [colorName, colorValue] of Object.entries(baseColors)) {
    baseValues.push(`--color-base-${colorName}: ${colorValue}`)
  }

  // console.log(baseValues);
  for (const color of Object.keys(themes)) {
    // console.log('building color', color);
    for (const themeName of themeNames) {
      const varName = `color-${themeName}-${color}`;
      const targetVarName = `color-base-${themes[color][themeName]}`;
      const varAssignment = `--${varName}: var(--${targetVarName})`;
      themeValues[themeName].push(varAssignment);
      themeLocals[themeName].push(`--color-local-${color}: var(--${varName})`);
    }

    // build CSS for theme color assignments


  }

  const baseCSS = buildCSSString(baseValues, 'base theme colors');
  console.log(baseCSS)

  const themeCSS = (Object.entries(themeValues).map(theme => {
    return buildCSSString(theme[1], `theme: ${theme[0]}`)
  })).map(item => item + ";\n").join("")

  const localsCSS = (Object.entries(themeLocals).map(theme => {

    return `.theme-${theme[0]}{
    ${buildCSSString(theme[1], `theme: ${theme[0]}`)
      }
    }`
  })).join("\n");
  // console.log(themeValues)
  const outputCSS = `
  /* This file automatically generated by npm run build:tokens. Do not edit this file! */
:root{
  ${baseCSS}

  /* THEME COLORS */
  ${themeCSS}
}
  /* APPLY VARIABLES LOCALLY */
  ${localsCSS}

  
  `
  // console.log(outputCSS)
  return outputCSS;
}


console.log('building design tokens');
const finalCSS = await prettier.format(generateCSS(), { parser: "css" });

fs.writeFileSync('design-tokens/tokens.css', finalCSS);